### ISSUE TITLE
Is the number of this **special image** the same as its frame number in the video?

### ISSUE THREAD

**Issue by AmoAonA** [myoh97/DGPS#2]
![image](https://github.com/user-attachments/assets/23acc109-99fd-44c1-8988-608acee5896c)
Is the number of this **special image** the same as its frame number in the video?

**Comment by myoh97** [comment]
![seq26img135](https://github.com/user-attachments/assets/24e46163-780d-4782-abb3-82e897a12ca4)

Yes, this is the one.

Thanks for your interest.

**Comment by AmoAonA** [comment]
thanks! 
![image](https://github.com/user-attachments/assets/37074634-53e1-4c8c-8baf-84a1f1f60d32)
Could we check the figure number?
Is it seq26img351?

**Comment by myoh97** [comment]
![image](https://github.com/user-attachments/assets/ec3ce694-3d22-4b3c-aa81-88b5125cd80d)

:)

**Comment by AmoAonA** [comment]
I'm sorry!
It is 351, too.
thanks
